# Generated by Django 3.2.5 on 2021-07-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_university', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_study',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('study', 'Учится'), ('deducted', 'Отчислен'), ('work', 'Работает'), ('fired', 'Уволен')], default='s', help_text='статус ученика', max_length=10),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(db_index=True, max_length=200)),
                ('university_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.university')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.faculty'),
        ),
    ]
